export default {
  ATOM: {
    BUTTON: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
    CARD: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
    CHECKBOX: {
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
    },
    DATE_PICKER: {
      LIGHT: "light",
      DARK: "dark",
    },
    ICON: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
    TABLE: {
      LIGHT: "light",
      DARK: "dark",
      LIGHT_HIGHLIGHT: "light-highlight",
      DARK_HIGHLIGHT: "dark-highlight",
    },
    TEXT_FIELD: {
      LIGHT: "light",
      DARK: "dark",
    },
    RADIO: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
    SWITCH: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
  },
  MOLECULE: {
    ALERT: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
    CONTROL: {
      LIGHT: "light",
      DARK: "dark",
    },
    DIALOG: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
    MENU: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
  },
  ORGANISM: {
    DRAWER: {
      BRAND: "brand",
      CTA: "cta",
      INFO: "info",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
    FOOTER: {
      BRAND: "brand",
      CTA: "cta",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
    FORM: {
      BRAND: "brand",
      CTA: "cta",
      SUCCESS: "success",
      WARNING: "warning",
      DANGER: "danger",
      LIGHT: "light",
      DARK: "dark",
    },
    NAVBAR: {
      BRAND: "brand",
      LIGHT: "light",
      DARK: "dark",
      WHITE: "white",
      BLACK: "black",
    },
  },
  TEMPLATE: {
    TWO_COL: {
      FIFTY_FIFTY: "50/50",
      TWENTY_EIGHTY: "20/80",
      EIGHTY_TWENTY: "80/20",
      SIDEBAR_LEFT: "sidebar-left",
      SIDEBAR_RIGHT: "sidebar-right",
    },
    THREE_COL: {
      THIRTY_THIRTY_THIRTY: "33/33/33",
      TWENTY_FORTY_FORTY: "20/40/40",
      FORTY_FORTY_TWENTY: "40/40/20",
    },
  },
};
